### ISSUE TITLE
Remove  "ignore": ["**/components/ui/**"]

### ISSUE THREAD

**Issue by zommerberg** [haydenbleasel/ultracite#147]
My project utilizes components/ui folder structure and i dont want it to be ignored. 

The ultracite default config should not have and ignored files

I had some headache trying to understand why biome didnt work for my /ui folder so it would be nice if this line is either removed or explained somewhere

**Comment by haydenbleasel** [comment]
Great point, Ultracite shouldn't assume your component structure.
